name: macOS Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 手動実行用

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check environment
      run: |
        uname -a
        sw_vers
        gcc --version
        
    - name: Install dependencies
      run: |
        brew install openssl@3
        echo 'export LDFLAGS="-L/usr/local/opt/openssl@3/lib"' >> ~/.bash_profile
        echo 'export CPPFLAGS="-I/usr/local/opt/openssl@3/include"' >> ~/.bash_profile
        source ~/.bash_profile
        
    - name: Build
      run: |
        export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
        export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
        make
        
    - name: Test basic functionality
      run: |
        # 基本的な機能テスト
        ./node_network -n 1 -T -U -D -E -F &
        PID=$!
        sleep 5
        kill $PID || true
        
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: node_network-macos
        path: node_network