name: Simple Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev
      - name: Create Makefile
        run: |
          cat > Makefile << 'MAKEFILEEOF'
          CC = gcc
          CFLAGS = -Wall -Wextra -pthread
          LDFLAGS = -pthread -lcrypto

          SRCS = main.c node.c stun.c upnp.c discovery.c discovery_server.c enhanced_discovery.c nat_traversal.c firewall.c reliability.c security.c diagnostics.c dht.c rendezvous.c turn.c ice.c
          OBJS = $(SRCS:.c=.o)
          HDRS = node.h stun.h upnp.h discovery.h discovery_server.h enhanced_discovery.h firewall.h reliability.h security.h diagnostics.h dht.h rendezvous.h turn.h ice.h

          all: node_network

          node_network: $(OBJS)
          $(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

          %.o: %.c $(HDRS)
          $(CC) $(CFLAGS) -c $<

          clean:
          rm -f node_network *.o

          .PHONY: all clean
          MAKEFILEEOF
      - name: Debug
        run: |
          ls -la
          cat Makefile
      - name: Build
        run: make VERBOSE=1
