name: Simple Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev
      - name: Debug
        run: |
          ls -la
          cat Makefile
      - name: Fix Makefile
        run: |
          sed -i 's/^node_network:/\tnode_network:/' Makefile
          sed -i 's/^%.o:/\t%.o:/' Makefile
          sed -i 's/^clean:/\tclean:/' Makefile
          sed -i 's/^rm -f/\trm -f/' Makefile
          sed -i 's/^$(CC)/\t$(CC)/' Makefile
          cat Makefile
      - name: Build
        run: make VERBOSE=1
